-- CITI CASH BACK PLUS MASTERCARD
WHERE s.filename LIKE '%citi_cash_back_plus%'

-- CITI PREMIERMILES WORLD MASTERCARD
WHERE s.filename LIKE '%citi_premiermiles_worl%'

-- CITI REWARDS WORLD MASTERCARD
WHERE s.filename LIKE '%citi_rewards_world_mas%'

-- LADY'S SOLITAIRE CARD
WHERE s.filename LIKE '%lady%'

-- MAYBANK FAMILY & FRIENDS CARD
WHERE s.filename LIKE '%family%'

-- MAYBANK WORLD MASTERCARD
WHERE s.filename LIKE '%world_mastercard%'

-- PREFERRED PLATINUM VISA
WHERE s.filename LIKE '%preferred_platinum_visa%'

-- UOB ABSOLUTE CASHBACK AMEX
WHERE s.filename LIKE '%absolute_cashback%'

-- UOB EVOL
WHERE s.filename LIKE '%evol%'

-- UOB PRVI MILES VISA CARD
WHERE s.filename LIKE '%prvi_miles%'


CITI CASH BACK PLUS MASTERCARD
CITI PREMIERMILES WORLD MASTERCARD
CITI REWARDS WORLD MASTERCARD

MAYBANK FAMILY & FRIENDS CARD
MAYBANK WORLD MASTERCARD

UOB EVOL
UOB PRVI MILES VISA CARD
UOB ABSOLUTE CASHBACK AMEX
PREFERRED PLATINUM VISA
LADY'S SOLITAIRE CARD